env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
rules:
  'import/extensions': 'off'
  'import/no-unresolved': 'off'
  semi:
    - error
    - never
  'no-unreachable':
    - 'error'
  'no-unexpected-multiline':
    - 'error'
  'lines-between-class-members':
    - 'error'
    - 'always'
    - exceptAfterSingleLine: true
  'no-param-reassign':
    - 'error'
    - props: false
  indent: 'off'
  '@typescript-eslint/indent':
    - 'error'
    - 4  
  'react/jsx-indent':
    - 2
    - 4
  'react/jsx-indent-props':
    - 2
    - 4
  'import/no-extraneous-dependencies': 'off'
  'max-len':
    - 'error'
    - code: 140
  'no-plusplus': 'off'
  'object-curly-spacing':
    - 'error'
    - 'always'
  'no-shadow': 'off'
  '@typescript-eslint/no-shadow': 'error'
  'no-unused-vars': 'off'
  'key-spacing':
    - 2
    - singleLine:
        beforeColon: false
        afterColon: true
      multiLine:
        beforeColon: false
        afterColon: true
  '@typescript-eslint/space-before-blocks': 'error'
  'space-infix-ops': 'error'
  'no-restricted-syntax': 'off'
  'no-use-before-define': 'off'
  '@typescript-eslint/no-use-before-define': 'error'
  'consistent-return': [0]
  'no-await-in-loop': [0]
  'no-continue': [0]
  'class-methods-use-this': [0]
  'import/prefer-default-export': [0]
  '@typescript-eslint/type-annotation-spacing':
    - 'error'
    - after: true
      before: false
      overrides:
        arrow:
          before: true
          after: true
  'object-curly-newline':
    - 'error'
    - ObjectExpression:
        consistent: true
        minProperties: 3
      ObjectPattern:
        multiline: true
        minProperties: 3
      ImportDeclaration:
        multiline: true
        minProperties: 3
      ExportDeclaration:
        multiline: true
        minProperties: 3
  '@typescript-eslint/naming-convention':
    - error
    - selector: 'enum'
      format:
        - 'PascalCase'
    - selector: 'enumMember'
      format:
        - 'PascalCase'
    - selector: 'class'
      format:
        - 'PascalCase'
    - selector: 'function'
      format:
        - 'camelCase'
        - 'PascalCase'
    - selector: 'parameter'
      format:
        - 'camelCase'
        - 'PascalCase'
      leadingUnderscore: 'allow'
    - selector: 'interface'
      format:
        - 'PascalCase'
    - selector: 'typeLike'
      format:
        - 'PascalCase'
